# Generated by Django 5.2.1 on 2025-05-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_produto_criado_em_remove_produto_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao_preco', models.CharField(blank=True, max_length=100)),
                ('beneficios', models.TextField(help_text='Separe os itens com ponto e vírgula (;)')),
                ('destaque', models.BooleanField(default=False)),
            ],
        ),
    ]
