# Generated by Django 5.2.1 on 2025-05-30 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nome',
        ),
        migrations.AddField(
            model_name='curso',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos_imagens/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='titulo',
            field=models.CharField(default='Título Inicial', max_length=200),
            preserve_default=False,
        ),
    ]
