# Generated by Django 5.2.1 on 2025-05-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_curso_options_remove_curso_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='destaque',
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
